### ISSUE TITLE
[Online IDE] [TLS-client] : Compilation fails on online IDE.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-tls#32] opened 2016-12-09 10:32 UTC
Steps to reproduce:
1. Import into online IDE via "import from URL" and point to example's github link.
2. Select K64F for platform and compile.
3. Fails to find "EthernetInterface.h".

However, it passes when compiling with CLI tool.
Screenshot below:

![tls-client](https://cloud.githubusercontent.com/assets/17567812/21046050/a3faeb7a-bdfa-11e6-899a-ae726e975bc4.jpg)

**Comment by ciarmcom** [comment] 2016-12-12 16:49
ARM Internal Ref: IOTSSL-1124

**Comment by andresag01** [comment] 2017-01-24 16:10
Notes:
* This issue cannot be reproduced using command line tools (mbed-cli) or the exporter's makefiles (mbed export).
* mbed-os has changed since this bug was first raised, so now we have a different problem reported by the compiler when using the online IDE:
```
Error: Cannot open source input file "device.h": No such file or directory in "extras/tls-client/mbed-os.lib/platform/platform.h", Line: 27, Col: 21
```
* I have raised a bug report in mbed OS https://github.com/ARMmbed/mbed-os/issues/3636. I am closing this bug report as it is not directly related to mbed TLS or the example code.

**Closed by andresag01** 2017-01-24 16:10 UTC
Labels: bug, mirrored, tracking
