### ISSUE TITLE
Create online IDE projects for opaque keys examples

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbed-os-example-tls#155] opened 2018-03-09 15:29 UTC
Create online IDE projects for new [opaque keys examples](https://github.com/ARMmbed/mbed-os-example-tls/tree/feature-opaque-keys): pk_sign, pk_verify and tls-client-with-client-authentication.

**Comment by ciarmcom** [comment] 2020-10-13 13:56
@mazimkhan thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:38
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-23 13:39
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-28 14:38
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-04 17:57
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-09 18:19
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-14 21:28
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-19 21:30
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-25 06:33
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-30 06:33
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-12-05 08:32
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-12-10 08:33
@mazimkhan it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by 0xc0170** [comment] 2020-12-10 09:12
This has not been fixed for more than 2 years, I'll close as "won't fix".

**Closed by 0xc0170** 2020-12-10 09:12 UTC
Labels: enhancement
