### ISSUE TITLE
[Online IDE] [Benchmark]: Compilation fails for Nuvoton NUC472.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-tls#33] opened 2016-12-09 14:45 UTC
Steps to reproduce:
1. Import example from the "import via URL" link and point to https://github.com/ARMmbed/mbed-os-example-tls.git
2. Change platform to Nuvoton NUC472. Remove other examples from workspace.
3. Compile.
4. Fails with following error.

![benchmark_onlineide](https://cloud.githubusercontent.com/assets/17567812/21052696/1b796f6e-be1e-11e6-8e34-7c2ce72ef54d.jpg)

**Comment by ciarmcom** [comment] 2016-12-12 16:49
ARM Internal Ref: IOTSSL-1123

**Comment by andresag01** [comment] 2017-01-24 16:41
Notes:
* This issue cannot be reproduced using command line tools (mbed-cli) or the exporter's makefiles (mbed export).
* The compilation error can still be reproduced with the HEAD of master branch in this repo.
* I have raised a bug report in mbed OS ARMmbed/mbed-os#3637. I will not close this bug yet as it is related to the mbed TLS implementation of hardware entropy in mbed OS.

**Comment by andresag01** [comment] 2017-01-26 13:51
The cause of the problem reported here is that the online IDE cannot handle multiple examples under the same project directory. Instead of importing the mbed TLS examples from their GitHub repo, use the following mirrors:
* https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-tls-benchmark
* https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-tls-tls-client
* https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-tls-hashing
* https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-tls-authcrypt

I will add links to these mirrors to the mbed TLS example's documentation.

**Comment by andresag01** [comment] 2017-01-26 14:19
I have created a PR to change the main README.md: https://github.com/ARMmbed/mbed-os-example-tls/pull/42

**Comment by andresag01** [comment] 2017-01-27 10:23
PR has been merged. Closing this issue.

**Closed by andresag01** 2017-01-27 10:23 UTC
Labels: bug, mirrored, tracking
