### ISSUE TITLE
Cannot export to uvision5, platform UBLOX_EVK_ODIN_W2

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/mbed-os-example-tls#67] opened 2017-03-14 08:10 UTC
commands:
cd benchmark
mbed export -i uvision5 -m UBLOX_EVK_ODIN_W2

the export log is only "scan ." and the project is nearly empty.

**Comment by andresag01** [comment] 2017-03-14 10:23
@theotherjimmy: Is this the expected behaviour? I ran the command and I get the following output:
```

**Comment by ashok-rao** [comment] 2017-03-14 12:33
@andresag01 .. The exported project does not contain anything except 1 file (mbed_config.h)...

**Comment by andresag01** [comment] 2017-03-14 12:55
@ashok-rao: That is interesting. I ran the same test and I got the files that I listed above. Perhaps it would be useful if you can post some additional information regarding your environment to help reproduce the issue. For example, what mbed-cli version are you using? what OS are you running? etc.

**Comment by ashok-rao** [comment] 2017-03-14 13:02
@andresag01 , when I run export, I get the *.uvprojx & *.uvoptx (which are the project files for uVision). When I open the project with MDK, there is nothing ..

![mdk](https://cloud.githubusercontent.com/assets/17567812/23901722/612d66d6-08b6-11e7-8cd9-87abced53e5d.JPG)

**Comment by andresag01** [comment] 2017-03-14 13:08
@ashok-rao: Thanks for the additional information. Perhaps @theotherjimmy can help us with this problem?

**Comment by theotherjimmy** [comment] 2017-03-14 16:38
again, https://github.com/ARMmbed/mbed-os/pull/3924 is the solution.

**Comment by mehdiBezahaf** [comment] 2017-03-29 12:17
Had the same problem and ARMmbed/mbed-os#3924 fixed it ;) Thanks

**Comment by andresag01** [comment] 2017-06-07 12:14
I have tried this with mbed OS 5.4.6 and the issue seems to be fixed. Closing this ticket...

**Closed by andresag01** 2017-06-07 12:14 UTC
