### ISSUE TITLE
client-tls: Test fail K64F for export to GCC OoB#4

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/mbed-os-example-tls#9] opened 2016-08-01 09:35 UTC
Platform: K64F
Tag: mbed-os-5.1.0-rc4
OS: OSX (10.11.6)
Test: client-tls

Test passes just fine when compiled with mbed (GCC_ARM) but when exported to GCC_ARM and compiled with make I'm getting:
```
Using Ethernet LWIP
Client IP Address is 10.2.203.154
Connecting with developer.mbed.org
Starting the TLS handshake...
mbedtls_ssl_handshake() failed: -0x0001 (-1): UNKNOWN ERROR CODE (0001)
MBED: Socket Error: -1
```

**Comment by sbutcher-arm** [comment] 2016-09-06 11:36
This looks like a network error and basically a mistest. To retest, I would suggest reproducing the fault with the a board and then using the exact same physical network connection, bringing up the homepage of [https://developer.mbed.org/](https://developer.mbed.org/) That is all the example does really.

We've tested this quite a bit, and it's a simple sample so I am confident it works as intended, so I'm going to close this issue.

If you feel there is a real issue, please feel free to reopen the issue and we can look again at it.

**Closed by sbutcher-arm** 2016-09-06 11:36 UTC
Labels: bug, mirrored
